export const productModel = {
  id: 0,
  name: "",
  description: "",
  price: 0.0,
  stock: 0,
  productType: "",
  mark: "",
  model: "",
  sizes: [],
  color: "",
  gender: "",
  img: "",
  status: true,
  code: "",
};

export const productModelCreateFormulary = {
  name: "",
  description: "",
  price: 0.0,
  stock: 0,
  productType: "PLANAS",
  mark: "",
  model: "SANDALIAS",
  sizes: [],
  color: [],
  gender: "DAMA",
  img: "",
  status: true,
  code: "",
};